"""add new models

Revision ID: e2ae7a9369b6
Revises: f9a263cf23a7
Create Date: 2023-08-28 18:48:36.817326

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2ae7a9369b6'
down_revision: Union[str, None] = 'f9a263cf23a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(length=100), nullable=False),
        sa.Column('hashed_password', sa.String(length=500), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'rooms',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('hotel_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.String(length=3000), nullable=True),
        sa.Column('price', sa.Integer(), nullable=False),
        sa.Column('services', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('image_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'bookings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('room_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('date_from', sa.Date(), nullable=False),
        sa.Column('date_to', sa.Date(), nullable=False),
        sa.Column('price', sa.Integer(), nullable=False),
        sa.Column('total_cost', sa.Integer(), sa.Computed('(date_to - date_from) * price', ), nullable=False),
        sa.Column('total_days', sa.Integer(), sa.Computed('date_to - date_from', ), nullable=False),
        sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.add_column('hotels', sa.Column('name', sa.String(length=60), nullable=False))
    op.add_column('hotels', sa.Column('location', sa.String(length=500), nullable=False))
    op.add_column('hotels', sa.Column('services', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('hotels', sa.Column('rooms_quantity', sa.Integer(), nullable=False))
    op.add_column('hotels', sa.Column('image_id', sa.Integer(), nullable=False))
    op.drop_column('hotels', 'Rooms quantity')
    op.drop_column('hotels', 'Hotel name')
    op.drop_column('hotels', 'Hotel services')
    op.drop_column('hotels', 'Hotel location')
    op.drop_column('hotels', 'Hotel image id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('Hotel image id', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.add_column('hotels', sa.Column('Hotel location', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('hotels', sa.Column('Hotel services', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False,
                                      nullable=False))
    op.add_column('hotels', sa.Column('Hotel name', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
    op.add_column('hotels', sa.Column('Rooms quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('hotels', 'image_id')
    op.drop_column('hotels', 'rooms_quantity')
    op.drop_column('hotels', 'services')
    op.drop_column('hotels', 'location')
    op.drop_column('hotels', 'name')
    op.drop_table('bookings')
    op.drop_table('rooms')
    op.drop_table('users')
    # ### end Alembic commands ###
